#!/bin/bash

echo "Restarting webserver"

echo "The following node processes were found:"

ps aux | grep " node " | grep -v grep
nodepids=$(ps aux | grep " node " | grep -v grep | cut -c10-15)

echo "OK, so we will stop these process/es now..."

for nodepid in ${nodepids[@]}
do
echo "Stopping PID :"$nodepid
kill -9 $nodepid
done
echo "Webservers stopped"

echo "Restarting webserver ..."

# start webserver
node scripts/webserver.js
# smoketest the webserver
cURL localhost:8080

echo "Restarting VNC Server"

# Stop VNC Server
sudo systemctl stop vncserver-x11-serviced.service #systemd
/etc/init.d/vncserver-x11-serviced stop #initd

# Start VNC Server
sudo systemctl start vncserver-x11-serviced.service #systemd
/etc/init.d/vncserver-x11-serviced start #initd

echo "Reboot completed"