name: Pre-Deployment

on:
  push:
    branches:
      - "master"

jobs:
<<<<<<< HEAD
  pre_deploy:
=======
  deploy:
>>>>>>> ac453627b6efbd46322e025fa0564c1edd20b7c7
    name: Check devices are online
    runs-on: ubuntu-latest
    steps:
      - name: Ping yellow station
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://${{ secrets.DEVICE_IP }}/commands/ping"
          method: "POST"
          bearerToken: Bearer ${{ secrets.DEVICE_TOKEN }}
